name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    if: github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69 # v5
        with:
          python-version: '3.11'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@d0c539 # release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
